### ISSUE TITLE
Request for Docker tags

### ISSUE THREAD

**Issue by dfego** [crazy-max/docker-osxcross#20]
Hi there! I was using the built containers here (thanks for making them available!) and after a recent update, my local builds failed because the paths updated with the new version of the SDK. At present, I have no way to stay on a particular build, so my only recourse is to take this repository and build my own, or update my project for the new SDK after it breaks.

So the request is to add tags, perhaps based on the included SDK version, for the built docker images on Dockerhub.

**Comment by crazy-max** [comment]
What tag did you use? And when did you pulled it when it worked?

**Comment by dfego** [comment]
Okay so I've looked through the tags on dockerhub before, but I somehow missed that there were numbered releases as I just requested. I saw the latest and edge ones and missed the others. So embarrassing, sorry for taking your time, and thanks for _already_ having the requested feature!
