### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by pratikbalar** [crazy-max/docker-osxcross#4]
Can you give an example of this with any one of your project ?

**Comment by crazy-max** [comment]
@pratikbalar Here are some of them:

* https://github.com/crazy-max/goxx/blob/main/examples/gorm/Dockerfile
* https://github.com/crazy-max/goreleaser-xx/blob/master/demo/cpp-goxx/Dockerfile

**Comment by zepadovani** [comment]
Hi, 

I'm not really used to docker and I'm trying to understand how can I interact with the image of the container os docker-osxcross to compile a test file from my terminal (I'm on linux).

Trying variations of `docker run <image>` does not work.

(Please sorry if it sounds stupid but it would really help me to understand how to properly run the image to run the binaries inside the docker you provided)

thanks in advance!
