### ISSUE TITLE
Missing GCC compilers

### ISSUE THREAD

**Issue by daniel-brenot** [crazy-max/docker-osxcross#40]
As the issue name suggests, this is missing the binaries for GCC compilers, which is supported by osxcross.

These can usually be built with build_gcc.

If i can manage to figure it out, i'll add support for this and make a pull request.

**Comment by crazy-max** [comment]
Sure feel free to open a PR

**Comment by crazy-max** [comment]
Actually I don't think we need anything in this repo as we just ship osxcross and osx sdk. It's up to you in your Dockerfile to install either gcc or clang as described in the README: https://github.com/crazy-max/docker-osxcross?tab=readme-ov-file#usage
